### ISSUE TITLE
El link de recuperar contraseña te manda a un dialogo en ingles

### ISSUE THREAD

**Issue by BernabeFelix** [BernabeFelix/todalasemana2.0#48]

**Comment by paulsancer** [comment]
There is a way to make your own password reset handler (the link in the email would directly send the user to the app and the app can validate the security code by itself). See this [SO Question](https://stackoverflow.com/questions/37932983/firebase-customize-reset-password-landing-page) for reference.

**Comment by paulsancer** [comment]
https://firebase.google.com/docs/auth/custom-email-handler

Turns out, I would have to change all email related stuff to be handled in the app (signup, psw reset and email change). In order to make it work, I have to set a new url for handling those operations but if I set it to `localhost` I will break everything in a server, and if I change it to the server, I break development... 

Not cool at all, that may lead to confusions and mistakes, will have to make another project with different keys and references for development...

**Comment by BernabeFelix** [comment]
I don't see why you need to change everything instead of just password reset. I don't see either why you will break everything in the server if localhost is used, we just need to be careful to have the correct value and testing is going to be needed to be done at night or something for that particular part

**Comment by paulsancer** [comment]
If I change that URL, it will be a change for all those three handlers: email verification, password reset and email change (<-- which we don't even have yet), there is no particular url for each operation just a query string parameter.

Firebase will send `mode` and security token to that url, being `mode` the action to take (email verification, pswd reset,...). So, our current mechanism for email verification will have to be handled in there too, meaning if we change that, the app at http://allweek.southcentralus.cloudapp.azure.com/ will lack that functionality in the meantime.

Give me a green light to change it and I will have all code ready for testing tomorrow night or if it is more urgent, I can create a `development` project in firebase. Your call.

**Comment by BernabeFelix** [comment]
Go, tomorrow night is fine
