### ISSUE TITLE
Remove duplicated Code

### ISSUE THREAD

**Issue by BernabeFelix** [BernabeFelix/todalasemana2.0#57]
In Header there are 2 Menu components that are copies of the ones in CustomerAdmin and SuperAdmin. 
Why are these copies and not just implementations?

**Comment by paulsancer** [comment]
The menus work different, the ones in admin sections use relative urls from where you are and that is fine since those menus shows there only, but header menu is shown everywhere and can't use the routes/urls that way, plus the header one has to implement a way to close itself but the admin one should not close.

What do you think? @BernabeFelix

**Comment by paulsancer** [comment]
However, I noticed one of mine is still using `containerElement` for `<Link />`  so I will change that to wrap the `MenuItem` inside the `<Link />`. See #70
